<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SignAssembly>True</SignAssembly>    
    <AssemblyOriginatorKeyFile>EPPlusTest.snk</AssemblyOriginatorKeyFile>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
    <PackageReference Include="FakeItEasy" Version="9.0.1" />
	<PackageReference Include="System.Resources.Extensions" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\BitmapImage.gif" />
    <None Remove="Resources\Test1.jpg" />
    <None Remove="Resources\Vector Drawing.wmf" />
    <None Remove="Resources\Vector Drawing2.wmf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BitmapImage.gif" />
    <EmbeddedResource Include="Resources\Test1.jpg" />
    <EmbeddedResource Include="Resources\Vector Drawing.wmf" />
    <EmbeddedResource Include="Resources\Vector Drawing2.wmf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPlus\EPPlus.csproj" />
  </ItemGroup>

</Project>
